server:
  port: 8080
  read_timeout: 5000
  write_timeout: 5000

etcd:
  endpoints:
    - etcd:2379
  dial_timeout: 5000

mongodb:
  host: mongo:27017
  dial_timeout: 5000
  db_name: crontab
  collection: logs
